/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TransactionsInterface extends ethers.utils.Interface {
  functions: {
    "addToBlockchain(address,uint256,string,string)": FunctionFragment;
    "getAllTransactions()": FunctionFragment;
    "getTransactionCount()": FunctionFragment;
    "transactions(uint256)": FunctionFragment;
    "transactionsCount()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addToBlockchain",
    values: [string, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionsCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addToBlockchain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactionsCount",
    data: BytesLike
  ): Result;

  events: {
    "Transfer(address,address,uint256,string,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export class Transactions extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TransactionsInterface;

  functions: {
    addToBlockchain(
      receiver: string,
      amount: BigNumberish,
      message: string,
      keyword: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, BigNumber, string, BigNumber, string] & {
          sender: string;
          receiver: string;
          amount: BigNumber;
          message: string;
          timestamp: BigNumber;
          keyword: string;
        })[]
      ]
    >;

    getTransactionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string, BigNumber, string] & {
        sender: string;
        receiver: string;
        amount: BigNumber;
        message: string;
        timestamp: BigNumber;
        keyword: string;
      }
    >;

    transactionsCount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addToBlockchain(
    receiver: string,
    amount: BigNumberish,
    message: string,
    keyword: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAllTransactions(
    overrides?: CallOverrides
  ): Promise<
    ([string, string, BigNumber, string, BigNumber, string] & {
      sender: string;
      receiver: string;
      amount: BigNumber;
      message: string;
      timestamp: BigNumber;
      keyword: string;
    })[]
  >;

  getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

  transactions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, string, BigNumber, string] & {
      sender: string;
      receiver: string;
      amount: BigNumber;
      message: string;
      timestamp: BigNumber;
      keyword: string;
    }
  >;

  transactionsCount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addToBlockchain(
      receiver: string,
      amount: BigNumberish,
      message: string,
      keyword: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<
      ([string, string, BigNumber, string, BigNumber, string] & {
        sender: string;
        receiver: string;
        amount: BigNumber;
        message: string;
        timestamp: BigNumber;
        keyword: string;
      })[]
    >;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string, BigNumber, string] & {
        sender: string;
        receiver: string;
        amount: BigNumber;
        message: string;
        timestamp: BigNumber;
        keyword: string;
      }
    >;

    transactionsCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    Transfer(
      from?: null,
      receiver?: null,
      amount?: null,
      message?: null,
      timestamp?: null,
      keyword?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber, string],
      {
        from: string;
        receiver: string;
        amount: BigNumber;
        message: string;
        timestamp: BigNumber;
        keyword: string;
      }
    >;
  };

  estimateGas: {
    addToBlockchain(
      receiver: string,
      amount: BigNumberish,
      message: string,
      keyword: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAllTransactions(overrides?: CallOverrides): Promise<BigNumber>;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transactionsCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addToBlockchain(
      receiver: string,
      amount: BigNumberish,
      message: string,
      keyword: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransactionCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transactionsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
